interface CountryFlagProps {
    origin: string;
    height: number;
    width: number;
}

function get_country_code(origin) {
    var array = Array(
        "Afghanistan", "AF",
        "Åland Islands", "AX",
        "Albania", "AL",
        "Algeria", "DZ",
        "American Samoa", "AS",
        "Andorra", "AD",
        "Angola", "AO",
        "Anguilla", "AI",
        "Antarctica", "AQ",
        "Antigua and Barbuda", "AG",
        "Argentina", "AR",
        "Armenia", "AM",
        "Aruba", "AW",
        "Australia", "AU",
        "Austria", "AT",
        "Azerbaijan", "AZ",
        "Bahamas", "BS",
        "Bahrain", "BH",
        "Bangladesh", "BD",
        "Barbados", "BB",
        "Belarus", "BY",
        "Belgium", "BE",
        "Belize", "BZ",
        "Benin", "BJ",
        "Bermuda", "BM",
        "Bhutan", "BT",
        "Bolivia", "BO",
        "Bosnia and Herzegovina", "BA",
        "Botswana", "BW",
        "Bouvet Island", "BV",
        "Brazil", "BR",
        "British Indian Ocean Territory", "IO",
        "Brunei Darussalam", "BN",
        "Bulgaria", "BG",
        "Burkina Faso", "BF",
        "Burundi", "BI",
        "Cambodia", "KH",
        "Cameroon", "CM",
        "Canada", "CA",
        "Cape Verde", "CV",
        "Cayman Islands", "KY",
        "Central African Republic", "CF",
        "Chad", "TD",
        "Chile", "CL",
        "China", "CN",
        "Christmas Island", "CX",
        "Cocos (Keeling) Islands", "CC",
        "Colombia", "CO",
        "Comoros", "KM",
        "Congo", "CG",
        "Congo, The Democratic Republic of the", "CD",
        "Cook Islands", "CK",
        "Costa Rica", "CR",
        "Cote D'Ivoire", "CI",
        "Croatia", "HR",
        "Cuba", "CU",
        "Cyprus", "CY",
        "Czech Republic", "CZ",
        "Denmark", "DK",
        "Djibouti", "DJ",
        "Dominica", "DM",
        "Dominican Republic", "DO",
        "Ecuador", "EC",
        "Egypt", "EG",
        "El Salvador", "SV",
        "Equatorial Guinea", "GQ",
        "Eritrea", "ER",
        "Estonia", "EE",
        "Ethiopia", "ET",
        "Falkland Islands (Malvinas)", "FK",
        "Faroe Islands", "FO",
        "Fiji", "FJ",
        "Finland", "FI",
        "France", "FR",
        "French Guiana", "GF",
        "French Polynesia", "PF",
        "French Southern Territories", "TF",
        "Gabon", "GA",
        "Gambia", "GM",
        "Georgia", "GE",
        "Germany", "DE",
        "Ghana", "GH",
        "Gibraltar", "GI",
    )
}

export default function CountryFlag({ origin, height, width }) {
    var img_src = "https://flagsapi.com/" + get_country_code(origin) + "/shiny/64.png";
    return (
        <img src={img_src} width={width} height={}></img>
    );
}
